// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Refresh_Token_adding : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Refresh_Token_adding));
        
        string IMigrationMetadata.Id
        {
            get { return "202601221745219_Refresh_Token_adding"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
